name: Automated test and lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  automated-test-and-lint:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint with Pylint
        continue-on-error: true
        run: >
          pylint --enable=F,E,C,R,W --disable=invalid-name,broad-except,logging-fstring-interpolation,protected-access
          --unsafe-load-any-extension=y --max-line-length=88 super_gcd 
      - name: Test with pytest
        run: |
          pytest
